### ISSUE TITLE
Domain kml-color.bazookatrip.xyz doesnt work anymore

### ISSUE THREAD

**Issue by logical-and** [approximatenumber/kml-color#1]
I can point my domain to your server or deploy or share VPS if that works

**Comment by approximatenumber** [comment]
@logical-and hi
yes, this domain is out of order, sorry
you can try http://kmlcolor.scrolllock.dev

**Comment by logical-and** [comment]
![image](https://user-images.githubusercontent.com/1403109/56869107-97c20880-6a04-11e9-86d9-61e333553929.png)

**Comment by approximatenumber** [comment]
Yes, I had some troubles with my DNS over https settings after domain migration. Please try again: https://kmlcolor.scrolllock.dev/

**Comment by logical-and** [comment]
Yay, that works fine for me. Thanks 👍 

(nice pic from Venice I suppose ;))
